---
# https://github.com/logsearch/bosh-silo-aws
director_uuid: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
name: "logsearch-standalone-test"

releases:
  - name: "logsearch"
    version: "latest"
  - name: "testutils"
    version: "latest"

update:
  canaries: 1
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000
  max_in_flight: 4

jobs:
  - name: standalone
    templates:
      - release: "logsearch"
        name: "ingestor_syslog"
      - release: "logsearch"
        name: "queue"
      - release: "logsearch"
        name: "log_parser"
      - release: "logsearch"
        name: "elasticsearch"
    instances: 1
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"
  - name: shipper
    templates:
      - release: "testutils"
        name: "testutils-data"
      - release: "testutils"
        name: "testutils-keys"
      - release: "testutils"
        name: "testutils-root"
    instances: 1
    resource_pool: "silo-t2-medium-private"
    networks:
      - name: "silo-private"
    properties:
      testutils:
        data:
          - /home/vcap/messages.log: |
              <%= File.read('src/sample-logs/repo-commits/messages.log').gsub(/^/, '              ').strip %>
              # EOF
          - /home/vcap/logstash.conf: |
                                      input {
                                        file {
                                          path => "/home/vcap/messages.log"
                                          sincedb_path => "/home/vcap/.sincedb"
                                          start_position => "beginning"
                                        }
                                      }
                                      
                                      output {
                                        if "# EOF" == [message] {
                                          exec {
                                            command => "/bin/bash -c '( sleep 5 ; sudo killall -s TERM java ) &'"
                                          }
                                        }
                                        
                                        syslog {
                                          facility => "user-level"
                                          host => "0.standalone.silo-private.logsearch-standalone-test.bosh"
                                          port => 5424
                                          rfc => "rfc5424"
                                          severity => "informational"
                                          sourcehost => "shipper"
                                        }
                                      }

properties:
  api:
    port: 80
  kibana:
   elasticsearch: "127.0.0.1:9200"
   port: 5601
  elasticsearch:
    host: "127.0.0.1"
    cluster_name: "logsearch-sanity-test"
  redis:
    host: "127.0.0.1"
  logstash_parser:
    filters: |
             mutate {
               rename => [ "syslog_message", "@message" ]
             }
             
             <%= File.read('src/sample-logs/repo-commits/logstash-filters.conf').gsub(/^/, '             ').strip %>
  logstash_ingestor:
    syslog:
      port: 5424
