---
name: develop-e2e

releases:
- name: logsearch
  version: dynamic

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  serial: true
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

resource_pools:
- name: warden
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

jobs:
- name: api
  release: logsearch
  templates:
  - name: elasticsearch
  - name: api
  - name: kibana
  update:
    serial: true
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.2
  properties:
    elasticsearch:
      node:
        allow_data: false

- name: ingestor
  release: logsearch
  templates:
  - name: ingestor_lumberjack
  - name: ingestor_syslog
  - name: ingestor_relp
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.14

- name: queue
  release: logsearch
  templates:
  - name: queue
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.10

- name: parser
  release: logsearch
  templates:
  - name: parser
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway

- name: elasticsearch_persistent
  release: logsearch
  templates:
  - name: elasticsearch
  update:
    serial: true
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.6
  persistent_disk: 1024
  properties:
    elasticsearch:
      node:
        allow_master: false

- name: elasticsearch_autoscale
  release: logsearch
  templates:
  - name: elasticsearch
  update:
    serial: true
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    elasticsearch:
      node:
        allow_master: false

- name: test_e2e_errand
  lifecycle: errand
  release: logsearch
  templates:
  - name: test_e2e_errand
  instances: 1
  resource_pool: warden
  networks:
  - name: default
  properties:
    test_e2e_errand:
      syslog_host: "10.244.2.14"
      syslog_port: 5514
      elasticsearch_hostport: "10.244.2.2:9200"

properties:
  api:
    port: 80
  kibana:
   elasticsearch: 127.0.0.1:9200
   port: 5601
  elasticsearch:
    host: 10.244.2.2
    cluster_name: logsearch--bosh-lite
    drain: true
    indices:
      ttl_interval: "5m"  # We want documents from test runs to be cleaned up frequently
    exec:
      environment:
        ES_HEAP_SIZE: 256M
  redis:
    host: 10.244.2.10
  logstash_parser:
    debug: true
    filters: |
             # src/sample-logs/repo-commits/logstash-filters.conf
             <%= File.read("#{Dir.glob('/tmp/build/*/src').first}/src/sample-logs/repo-commits/logstash-filters.conf").gsub(/^/, '             ').strip %>
  logstash_ingestor:
    debug: true
    relp:
      port: 5515
    syslog:
      port: 5514
    syslog_tls:
      port: 443
      # ingestor-20241214a
      ssl_cert: |
          -----BEGIN CERTIFICATE-----
          MIICWjCCAcOgAwIBAgIJAN57Q1O2B6k0MA0GCSqGSIb3DQEBBQUAMG0xFTATBgNV
          BAoMDGxvZ3NlYXJjaC5pbzEeMBwGA1UECwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5
          MREwDwYDVQQDDAhpbmdlc3RvcjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w
          bGUuY29tMB4XDTE0MTIxNzIyMDkyNloXDTI0MTIxNDIyMDkyNlowXDEVMBMGA1UE
          CgwMbG9nc2VhcmNoLmlvMQ0wCwYDVQQLDARURVNUMREwDwYDVQQDDAhpbmdlc3Rv
          cjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3
          DQEBAQUAA4GNADCBiQKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjC
          ATC6F6ZaKCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwova
          yLEQRGMvZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13
          GQIDAQABoxMwETAPBgNVHREECDAGhwQK9AIOMA0GCSqGSIb3DQEBBQUAA4GBAFLV
          Z59nPFO1+W407lDCm4tXV3RpUCt4drAqNp1xum6U9fkcgzU0ZhrfmVCqGdFGWxxM
          Jhe1iAbho/Jb85V9hB9txr2Uh5Xvr0r0faeJYqFF+NCc9G+PKiNVwbId0rH2bfwr
          YLxYAgzDDozZ1bUSUQKbkiX8jSQHB63MPZXSAMWb
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIICXAIBAAKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjCATC6F6Za
          KCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwovayLEQRGMv
          ZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13GQIDAQAB
          AoGAHX57Flgic+f2hJ05bVYZaTFN1Lndj5/W7Nr19rajZil+QQzuGNVovrrD2dNb
          g+wF9OUoWJ15kkpJRrA6gVTDIYgZwoWjpo1X6NKfiMGbtITSePfwB17egeaVvoKW
          nxfhd5absxOAC13hXNGEIyklzBMzyikTbrlemeo07gLq+H0CQQDWzxVTIXesjQ2S
          Um9vvsUdlxqU5AjvsVPDZP3/d3NYF0ZALyyeqg1mE+pc4gEXw3T5Q5IMyxxFZjqQ
          m2mpuZzDAkEAxNbXko2mSopYZ5/LR6KJFvze8t70b0TUvlvPvM3M6pMeViqSrfyt
          QvHMNPRxbgoniNwm7W9x6Jp2UAUzH2kO8wJBAJc3KkTeH3fpx+8EdwwMGIkPERhV
          OvE5PMUlOCT5usn9gGe4jcmX3lzIkkgWlTxcTOEYLx0wclNsdrfLn+NqFa8CQByU
          xYB2KOsx41xIi4+/PgCkfwrs7LkrWWi6lBNqHpMBAaqpS9sPkWjjCy+1PrMnrk3l
          CZH4WKXZp8w+tQmei5kCQCxQ6Se1d1fSYQlLsCoTKmbcOjFoT5joj1nMIwSwn/Sy
          eevXlJLkedUMlEntH3b+dQjaRSWwWWtjzxY/Ou0CLKI=
          -----END RSA PRIVATE KEY-----
    lumberjack:
      # ingestor-20241214a
      ssl_certificate: |
          -----BEGIN CERTIFICATE-----
          MIICWjCCAcOgAwIBAgIJAN57Q1O2B6k0MA0GCSqGSIb3DQEBBQUAMG0xFTATBgNV
          BAoMDGxvZ3NlYXJjaC5pbzEeMBwGA1UECwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5
          MREwDwYDVQQDDAhpbmdlc3RvcjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w
          bGUuY29tMB4XDTE0MTIxNzIyMDkyNloXDTI0MTIxNDIyMDkyNlowXDEVMBMGA1UE
          CgwMbG9nc2VhcmNoLmlvMQ0wCwYDVQQLDARURVNUMREwDwYDVQQDDAhpbmdlc3Rv
          cjEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3
          DQEBAQUAA4GNADCBiQKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjC
          ATC6F6ZaKCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwova
          yLEQRGMvZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13
          GQIDAQABoxMwETAPBgNVHREECDAGhwQK9AIOMA0GCSqGSIb3DQEBBQUAA4GBAFLV
          Z59nPFO1+W407lDCm4tXV3RpUCt4drAqNp1xum6U9fkcgzU0ZhrfmVCqGdFGWxxM
          Jhe1iAbho/Jb85V9hB9txr2Uh5Xvr0r0faeJYqFF+NCc9G+PKiNVwbId0rH2bfwr
          YLxYAgzDDozZ1bUSUQKbkiX8jSQHB63MPZXSAMWb
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIICXAIBAAKBgQClKtJSXPwsPWPIhSFqPDcyQwvsIY/nF+vNjetX1xjCATC6F6Za
          KCcddF1JaomTiPR9+qVeNedGwvtcrCLyOYpqBWs6KuCq4dE/7QxEwovayLEQRGMv
          ZW8OClpjY0PdrpX+ekqllD/7CTMYvabc3Kq0Q6WPZAGLo01YoW2KKr13GQIDAQAB
          AoGAHX57Flgic+f2hJ05bVYZaTFN1Lndj5/W7Nr19rajZil+QQzuGNVovrrD2dNb
          g+wF9OUoWJ15kkpJRrA6gVTDIYgZwoWjpo1X6NKfiMGbtITSePfwB17egeaVvoKW
          nxfhd5absxOAC13hXNGEIyklzBMzyikTbrlemeo07gLq+H0CQQDWzxVTIXesjQ2S
          Um9vvsUdlxqU5AjvsVPDZP3/d3NYF0ZALyyeqg1mE+pc4gEXw3T5Q5IMyxxFZjqQ
          m2mpuZzDAkEAxNbXko2mSopYZ5/LR6KJFvze8t70b0TUvlvPvM3M6pMeViqSrfyt
          QvHMNPRxbgoniNwm7W9x6Jp2UAUzH2kO8wJBAJc3KkTeH3fpx+8EdwwMGIkPERhV
          OvE5PMUlOCT5usn9gGe4jcmX3lzIkkgWlTxcTOEYLx0wclNsdrfLn+NqFa8CQByU
          xYB2KOsx41xIi4+/PgCkfwrs7LkrWWi6lBNqHpMBAaqpS9sPkWjjCy+1PrMnrk3l
          CZH4WKXZp8w+tQmei5kCQCxQ6Se1d1fSYQlLsCoTKmbcOjFoT5joj1nMIwSwn/Sy
          eevXlJLkedUMlEntH3b+dQjaRSWwWWtjzxY/Ou0CLKI=
          -----END RSA PRIVATE KEY-----


# Warden CPI requires crappy network settings; so "hide" them away here
networks:
- name: default
  # Assumes up to 7 VMs, including 4 static and 3 dynamic.
  # Plus 7 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static:
    - 10.244.2.10
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static:
    - 10.244.2.14

  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.40/30
    reserved:
    - 10.244.2.41
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.44/30
    reserved:
    - 10.244.2.45
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.48/30
    reserved:
    - 10.244.2.49
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.52/30
    reserved:
    - 10.244.2.53
    static: []

apply_spec:
  properties:
    ntp:
      - 0.europe.pool.ntp.org
      - 1.europe.pool.ntp.org
      - 2.europe.pool.ntp.org
      - 3.europe.pool.ntp.org
