---
redis/redis-2.8.4.tar.gz:
  object_id: 191a0100-c082-4f96-9bb4-73abe803e649
  sha: 79b156cc9d8bff5a022fdc6d28d5c42999ddcb4f
  size: 1048914
java8/openjdk-1.8.0_40.tar.gz:
  object_id: c1386f34-7585-4f92-b41e-6d9dbbb940ab
  sha: 590be5c6337753b28acc81d4843e98e6245b5261
  size: 39630740
curator/click-3.3.tar.gz:
  object_id: 5a17f7ca-b4dc-467a-b5a3-9181dfba17b6
  sha: d716a932b930d71059e49465b6b42e833808369a
  size: 259855
curator/urllib3-1.8.3.tar.gz:
  object_id: f5601b3b-e555-4ca0-b955-c01e4081d0ee
  sha: 00c92b0c3b0756ae3c4e6262d5bc80023dfe9ca3
  size: 85466
python/Python-3.4.3.tgz:
  object_id: 34ff2b80-c2ca-4075-81a7-164805059d89
  sha: 94cae02a334c72ea6ba8c056bb2864e2838878d3
  size: 19554643
curator/elasticsearch-curator-3.4.0-dev1.tar.gz:
  object_id: 508de17f-8c5b-4baf-b3e7-63bcd73247dc
  sha: 8e75e27c24d5b05ff446e778ef9dd3b95c49c91b
  size: 137108
curator/elasticsearch-1.7.0.tar.gz:
  object_id: 3bdcfe3c-1af6-4777-9a15-2d053d172a15
  sha: 01b76bf67b47a0bcbb69a6d7d00169449f780484
  size: 62054
haproxy/haproxy-1.6.2.tar.gz:
  object_id: 48bf1c42-207b-4c26-90ca-eeca21f96787
  sha: 407bed920315cf66500ab57aea0c402bad850129
  size: 1538976
haproxy/pcre-8.38.tar.gz:
  object_id: 9538f6cf-5cd1-4551-a5c3-1263fb32edf6
  sha: 3ab418d0026c2a4e693ec783bd60660debc32b8f
  size: 2053336
elasticsearch/elasticsearch-2.2.0.tar.gz:
  object_id: 4bd686ed-b9e0-47d1-8437-78dac6fdc27c
  sha: 4bd3ef681e70faefe3a66c6eb3419b5d4a0e2714
  size: 29419005
kibana/kibana-4.4.0-linux-x64.tar.gz:
  object_id: 87e63448-e145-4844-b01a-9ede4d5c5389
  sha: 82fa06e11942e13bba518655c1d34752ca259bab
  size: 30878925
logstash/logstash-all-plugins-2.2.0.tar.gz:
  object_id: 5e7ecb2d-bca6-423c-b0f2-a197c3c1ceed
  sha: 1cb658c6e79332e5b2e96d6b5d89b5d7207fc6e2
  size: 129473672
