---
nginx/nginx-1.4.7.tar.gz:
  object_id: a3a064ab-84ea-4d3c-8bcf-28ba5be5c285
  sha: e13b5b23f9be908b69652b0c394a95e9029687e3
  size: 769153
nginx/pcre-8.33.tar.gz:
  object_id: 1be6421e-16f5-42fc-8ad6-2eb756cde679
  sha: bceafb53553219dad2593bb8af06da4d07fd3828
  size: 1889401
redis/redis-2.8.4.tar.gz:
  object_id: 191a0100-c082-4f96-9bb4-73abe803e649
  sha: 79b156cc9d8bff5a022fdc6d28d5c42999ddcb4f
  size: 1048914
elasticsearch/kibana-3.1.0.tar.gz:
  object_id: ad1b93da-2ae8-44f9-a62a-a26313aeb880
  sha: effc20c83c0cb8d5e844d2634bd1854a1858bc43
  size: 1073033
kibana/kibana-4.0.1-linux-x64.tar.gz:
  object_id: 9999d8fe-8031-4c68-8a9e-d1a77f9ecf58
  sha: 1b8914c62a606b7103295a4e3ab01ec40c9993ed
  size: 13625479
java8/openjdk-1.8.0_40.tar.gz:
  object_id: c1386f34-7585-4f92-b41e-6d9dbbb940ab
  sha: 590be5c6337753b28acc81d4843e98e6245b5261
  size: 39630740
logstash/logstash-filter-alter-0.1.6.gem:
  object_id: d96edc4c-ffdd-4fc8-9bae-1dc243b2e074
  sha: e2cadce7e3d145c791087832c4f647f451f5027e
  size: 8704
logstash/logstash-filter-translate-0.1.9.gem:
  object_id: 9848212e-40a3-4f46-b40d-407f5b94d2c3
  sha: 65e437fd64202ff879990d7c7963f3f7b4e50c17
  size: 10240
logstash/logstash-input-relp-0.1.5.gem:
  object_id: cf9789c1-f2dc-43ca-b0fa-8c53f1346184
  sha: eb4c73ac65bc39ea3d51b8473dfe69d263694fa9
  size: 11776
elasticsearch/elasticsearch-1.5.2.tar.gz:
  object_id: 89918f09-6f64-4e4f-aa39-3064313560fb
  sha: ffe2e46ec88f4455323112a556adaaa085669d13
  size: 28173132
logstash/logstash-1.5.0.tar.gz:
  object_id: 5dbd902b-49d4-40e5-a3b1-a240c5af017f
  sha: 9729c2d31fddaabdd3d8e94c34a6d1f61d57f94a
  size: 87008665
elasticsearch/elasticsearch-1.6.0.tar.gz:
  object_id: c305d75d-a100-4dfd-a619-b5c4ee31d0e9
  sha: cb8522f5d3daf03ef96ed533d027c0e3d494e34b
  size: 28401477
logstash/logstash-1.5.2.tar.gz:
  object_id: 36249fab-dcf7-45b1-9ecd-e2a842b93c9f
  sha: 92e4ce646ca6a1868bac56def5ddf096349ec0a6
  size: 91217160
kibana/kibana-4.1.1-linux-x64.tar.gz:
  object_id: c08909df-55f0-400a-bac6-399e309d70c0
  sha: d43e039adcea43e1808229b9d55f3eaee6a5edb9
  size: 11676499
