elasticsearch_data.*: logsearch
elasticsearch_master.*: logsearch
firehose-to-syslog.*: logsearch
ingestor.*: logsearch
kibana.*: logsearch
maintenance.*: logsearch
parser.*: logsearch
queue.*: logsearch
router.*: logsearch
monitor.*: logsearch
ls-router.*: logsearch
